### ISSUE TITLE
Basic: Profile selection screen UI tour

### ISSUE THREAD

**Issue by demonnic** [Mudlet/VideoPlanning#11]
# Script

Hello,

In this tutorial, I will cover all the elements of the profile selection window in Mudlet as of version 4.14, which is the latest release at the time of recording. 

When you first open Mudlet, you are presented with the profile selection screen. This is where you select which profile or game you wish to open. The list of profiles is here on the left. If you right click on a profile's icon, you can select to either set an image of your own for the profile, or set a custom color for the profile rather than the one automatically assigned by Mudlet on creation. If you double click on a profile it will open it.

Below that, we have the Remove, Copy, and New buttons. There is a drop down on the copy button which allows you to copy settings only, so you can keep the game information but not necessarily copy all the associated scripts and map files. 

Here in the top right, we have the block of required information. This consists of the profile name, the server address for it to connect to, and the port to connect to. If your game uses TLS to encrypt your connection with them, you will also need to check "secure". 

Here, we have the Profile history. Every time you save your Mudlet profile a new save file is created. By default, the most recent one is selected, but should something go wrong such as making a major error in your script, or a save file becomes corrupted, you can click to drop this down like so and select any of the previous copies of your profile. 

Below that are some additional options. There are fields to store your username and password for the game. If this is done Mudlet will hide them when they're entered. There is also one to enabled Discord integration, one to open the selected profile on Mudlet start, in which case this screen will not be shown and the autostart profile will start instead, and one which will cause it to reconnect automatically if disconnected.

Below that is an information box where you briefly describe the profile or the game it connects to.

Finally, there is the Connect, Offline, or Cancel buttons. Connect will open the profile and connect to the game. Offline will open the profile but not connect to the game, and Cancel will close the profile selection screen, though without a profile open there are limited actions you can take, namely opening a profile, connecting to Discord, or reading the about/help screens.

Let's finish up by briefly walking through creating a new profile. First, you click "New", then enter a name for the profile, in this case "Profile Tutorial". You would then enter a server address and port number. This is information you will generally get from your game. I'll put in mudlet.org, and use port 3000. At this point, you can fill in your username and password or adjust any of the other options below, but enough information has been filled in to click on connect, which will save the new profile with its connection information, open it, and try to connect to the game. In our case, it will fail, as there's no game listening for connections at that address and port combination, but you should be connected to your game and ready to begin at this point. 

In today's video, we went over the various elements of the Profile Selection screen and what each of them does, and then quickly created a new example profile. In future videos, we will go over the UI elements of the Main Window, and eventually how to go about creating your own customized User Interface with Mudlet.  I hope this video was informative and helpful, and I look forward to creating and sharing the next one with you all. Until then, happing MUDding.

## YouTube Links
720p  - https://youtu.be/CicyjFoy9q4
1080p - https://youtu.be/Ypwpx0XY94E

**Comment by Kebap** [comment]
This video is published - closed
