### ISSUE TITLE
Add to Youtube thumbnail pictures

### ISSUE THREAD

**Issue by Kebap** [Mudlet/VideoPlanning#18]
Most videos on Mudlet channel currently seem identical and are only distinguishable by reading the video title.

I suggest to put some differentiating item in the thumbnail pictures, while keeping it mostly the same.
This will serve two purposes: 
1) The players recognize the video is part of a longer series 
2) The players recognize the very video's topic more quickly

While playing around with the idea, I wonder which font we used for the Youtube header image? Did not find in other repo either.

![image](https://user-images.githubusercontent.com/117238/186249577-0e0d043a-c5a2-4f17-823b-68cec3f93e98.png)

See the latest video thumbnails at the bottom, most (but not all) look just the same.

(They also seem to have a wrong aspect ratio and cut off the top and bottom of the arch alright)

Here is a preliminary mockup how that could look like. I put the wrong font but hey.

![image](https://user-images.githubusercontent.com/117238/186252017-e6daabab-7442-4671-99ca-ce5b6f110b7e.png)

If we were to publish another video on triggers, it could gain a second line below and say "Triggers # 2" or alike.

Here's another list I made of all currently published videos in the series, and their short caption for the thumbnail:

1. Scripts: Basic Scripts
2. Windows: Download And Install Mudlet for Windows
3. Linux: Download And Install Mudlet for Linux
4. MacOS: Download And Install Mudlet for MacOS
5. Keys: Keybindings (Keyboard Macros)
6. RegEx: Basic Regular Expressions
7. Aliases: Basic Aliases
8. Triggers: Basic Substring Triggers
9. Profiles: Profile Selection Screen Tour

**Comment by demonnic** [comment]
It's a good idea, but we'll want to get an easy workflow established so we can churn out thumbnails without really having to think about it much.

**Comment by vadi2** [comment]
What about picking a thumbnail from the middle of the video?

**Comment by demonnic** [comment]
Those will inevitably look pretty samey too, I think. The editor and main window only change so much in a lot of these.

I wonder if I can make a thumbnail script in Mudlet to use Mudlet labels to create a thumbnail image given a title and subtitle. I think I might like that better than photoshopping a new one each time. Thoughts?

**Comment by vadi2** [comment]
That's a great idea.

**Comment by Kebap** [comment]
> photoshopping a new one each time

Literally goes like this:
- open photoshop from last time (actually I use Gimp instead)
- delete the old title, type the new
- save, done

You can replace Photoshop with Mudlet and write a script for that as well, but it won't be much less work.
The important decision is not the tool used but the layout we want to go for in the end.
I suggested one above but heard no feedback on that at all, at all.

Actually I assume Mudlet will be worse for graphic design than a program designed for well, exactly that.

**Comment by demonnic** [comment]
Yes, but I know Mudlet and I don't know gimp or photoshop really. I'd like not to have to learn yet another tool as part of doing these. Plus I feel like making them in Mudlet ties it back to the content/subject a little more tightly. 

I'd be tempted to use a nice monospace font rather than the more heavily stylized one. Generally speaking I feel like they're easier to read and monospace fonts are a MUD staple. But I don't dislike the stylized one listed from the header image. I wish I knew what it was to tell you though. 

All that being said if someone else is offering to do them then I'm a lot less picky all of a sudden about things like the tool used, etc.

**Comment by SlySven** [comment]
> I'd be tempted to use a nice monospace font rather than the more heavily stylized one. Generally speaking I feel like they're easier to read and monospace fonts are a MUD staple. But I don't dislike the stylized one listed from the header image. I wish I knew what it was to tell you though.

Do you mean the fancy font used for the word "Mudlet"? If so the glyphs for that were originally created by Thorsten Wells and he only did (AFAIK) 'M' 'u' 'd' 'l' 'e' and 't' - and that was in an .SVG format. I got the files (and they are at: https://github.com/Mudlet/artwork) and I think you can get them from https://github.com/Mudlet/artwork/blob/master/originals/splash.svg . With some careful editing I was able to use those to make a 'p' (by rotating the 'd') and a 'v' by manipulating the points in the 'u' to make the "ptb" and "dev" extra bits we needed for those splash screens but there is not a "complete" set of glyphs for even a basic alphabet font in existence...

**Comment by Kebap** [comment]
> if someone else is offering to do them 

Yes I can provide them. 
Super easy, barely an inconvenience. 
That is why I showed example layouts above.
I would have put them online already but wanted discussion first.

**Comment by vadi2** [comment]
You should have lead with that! 😅

@demonnic ?

**Comment by demonnic** [comment]
Sounds good to me =)

**Comment by Kebap** [comment]
So after discussing the tool used, and who could be doing the work, we still haven't decided on content or layout questions.

> use a nice monospace font

Care to name a few?

**Comment by Kebap** [comment]
Reviewing the last proposal and other channels' thumbnails, I came up with the need for fitting a "tag line" of sort in there as well.

Behold design 2 and 3 for your review:

Design 2:
![image](https://user-images.githubusercontent.com/117238/187029241-2da56b08-2c56-42e4-a435-1b2c66b38388.png)

Design 3:
![image](https://user-images.githubusercontent.com/117238/187031170-d07fdbe4-eca7-4ee5-8d12-8540bccc6bc5.png)

This uses the monospace font "Noto Mono"
(even though it is a bit contradicted by having the text align towards the center but hey)

Also 2 lines of possible tag line at the bottom.

**Comment by vadi2** [comment]
Thanks for doing this - I like the second one!

Idea - what about instead of a black background, we have a gradient-based dark background that is unique for each thumbnail? This will make them stand out and look appealing at the same time. We can use AI-based tools to generate it (there's lots of them - just [one example](https://app.wombo.art/) that works)

**Comment by Kebap** [comment]
Here's a different (kind of) text shown in Design 2 for comparison:

Video 2a

![image](https://user-images.githubusercontent.com/117238/187045264-f766404d-a7a2-487e-916e-1fa5dab6348c.png)

Video 2b

![image](https://user-images.githubusercontent.com/117238/187049003-89f1942e-a654-4d8d-87ea-6f588014b0d2.png)

**Comment by demonnic** [comment]
What about an outline font? Something like https://www.1001fonts.com/taurus-mono-outline-font.html maybe?  Or possibly https://www.1001fonts.com/origami-mommy-font.html? 

Just a thought.

**Comment by Kebap** [comment]
Fair enough. Let's try them.

Design 2b Taurus bold
![image](https://user-images.githubusercontent.com/117238/187095711-dfd33f39-d43e-48d4-ada1-061d03d4c460.png)

Design 2b Origami
![image](https://user-images.githubusercontent.com/117238/187095822-23f8829c-8195-4794-89ec-7fc39b8cca29.png)



Also let's take a look how these look in smaller size, because that is what most players will first (or only) see on Youtube:

Design 2b Taurus bold small
![image](https://user-images.githubusercontent.com/117238/187095693-c93eb906-96d0-45f6-beff-ceafba2f1f7a.png)

Design 2b Origami small
![image](https://user-images.githubusercontent.com/117238/187095810-16e38255-f767-4e92-820a-61fdb5edbd17.png)

**Comment by demonnic** [comment]
I kind of like the Taurus Bold, the origami one seems a little harder to read. I'm not sure if I like them much better than the ones you provided before though. I can see how some people might find them hard to read.

**Comment by vadi2** [comment]
Yeah, the thumbnails do look tough indeed. Could we have a thumbnail of Ubuntu Mono?

**Comment by Kebap** [comment]
Design 2b Ubuntu Mono bold thumbnail 120
![image](https://user-images.githubusercontent.com/117238/187244658-184c8f6a-74f4-44d8-81b9-198ec8d900f3.png)

This font seems not as wide as the ones above, therefore I could increase char size from 120 to 170 maybe

Design 2b Ubuntu Mono bold thumbnail 170
![image](https://user-images.githubusercontent.com/117238/187243949-db607acd-ad4f-4ab6-89be-e1aae8c05842.png)

Or let's mix them as there is more room at the top

Design 2b Ubuntu Mono bold thumbnail 170+120
![image](https://user-images.githubusercontent.com/117238/187245951-a4022161-9995-4072-89eb-a17d8e3a1133.png)

**Comment by vadi2** [comment]
I like the third one. What do others think?

**Comment by demonnic** [comment]
Same

**Comment by Kebap** [comment]
For the record, the other video content / description type.

Design 2a Ubuntu Mono bold thumbnail 170+120
![image](https://user-images.githubusercontent.com/117238/187261995-83d5d9e8-8236-4fe4-a097-0452464c8434.png)

**Comment by Kebap** [comment]
Talking captions, there is room for a tag line as well, so let's think of some concise but interesting ones:

| Video No. | Script | Youtube title (and link) | Thumbnail caption | Thumbnail tag line |
| --------- | ---- | ---------- | ----------------- | ------------------ |
| 1. | #7 | [Basic Aliases](https://youtu.be/Uz6EDvZYNvE) | Aliases | React to player input |
| 2. | #1 | [Download And Install Mudlet for Windows](https://youtu.be/BLem0ZD6yRo) |  (none) | Install on Windows |
| 3. | #6 | [Basic Regular Expressions](https://youtu.be/KFoax1Q0ltw) | RegEx | Regular Expressions |
| 4. | #2 | [Download And Install Mudlet for MacOS](https://youtu.be/Ug4I8gNUhdg) | (none) | Install on MacOS |
| 5. | #5 | [Keybindings (Keyboard Macros)](https://youtu.be/ZYRPZ-8fJWA) | Keys / Macros | Press any key to start your script |
| 6. | #3 | [Download And Install Mudlet for Linux](https://youtu.be/LIJuFra-KKc) |  (none) | Install on Linux |
| 7. | #4 | [Basic Scripts](https://youtu.be/10mJUh4Hq-A) | Scripts | Code with the power of Lua |
| 8. | #8 | [Basic Substring Triggers](https://youtu.be/jYjop54-Y3I) | Triggers | React to game output |
| 9. | #11 | [Profile Selection Screen Tour](https://youtu.be/CicyjFoy9q4) | Profiles | Connect to your game |

The "caption" I put in the top right corner, so it needs to be at best one brief word.

The "tag line" will be shown at the bottom of the thumbnail picture.
There is room for two lines of (short) text, or we had a logo, too.

Videos 3, 5, 7 and 9 do not have a tag line decided, yet. Looking for your input here!

**Comment by vadi2** [comment]
Do you mean 2,4, and 6?  Because the tag line column (last one) seems to be filled in fully?

**Comment by Kebap** [comment]
Well no, those are deliberately left blank, but I edited afterwards and put some ideas of my own in there meanwhile.

There is the current status and result of above brainstorm. Thanks to you all! 😄 

![image](https://user-images.githubusercontent.com/117238/187611637-656ef556-f83a-42f3-867e-5e702a86cff8.png)

**Comment by vadi2** [comment]
Awesome, thanks!

Could you add the thumbnail source files to the artwork repo?

**Comment by Kebap** [comment]
Done
