### ISSUE TITLE
Download and install (MacOS)

### ISSUE THREAD

**Issue by demonnic** [Mudlet/VideoPlanning#2]
## Script

Hello,

In this tutorial, I will cover how to download and install Mudlet for MacOS.

First, you'll need to open your web browser and navigate to https://www.mudlet.org/download , which will bring up the Mudlet download page. It should pre-select the proper tab for your operating system, but if not you can click on it here to bring it up.

Then click here to download the latest release, or here to download the latest Public Test Build, or PTB. The release is the current stable version of Mudlet, and good for most users. The PTB is our nightly build, and has all the latest features and updates but may be slightly less stable, and updates as often as once a day. 

Once the download is complete, open the dmg, and then drag the Mudlet icon over to Applications. Then open the Applications folder and open Mudlet. It will bring up a dialog asking if you are sure because it was downloaded from the internet, click 'open' and Mudlet will start, allowing you to select a game and start playing.

In today's video, we went over how to download and install Mudlet on MacOS. In future videos, we will explore the basics of scripting and interacting with your game via Lua, as well as the many other features Mudlet has. I hope this video was informative and helpful, and I look forward to creating and sharing the next one with you all. Until then, happing MUDding. 

## Link
https://youtu.be/Ug4I8gNUhdg

**Comment by vadi2** [comment]
:+1:
