### ISSUE TITLE
Basic keybindings

### ISSUE THREAD

**Issue by demonnic** [Mudlet/VideoPlanning#5]
# Script

first one recorded, had no script.

## Link

https://youtu.be/ZYRPZ-8fJWA

**Comment by vadi2** [comment]
It would be also good to link to a keypad movement script available off the shelf in the forums, in the videos description.

**Comment by demonnic** [comment]
Oh good idea, do we have one there already that you know of or should I upload one?

**Comment by demonnic** [comment]
found Oneymus' one from way back, should be good

**Comment by demonnic** [comment]
added
```
If you'd like to download a package which adds number pad movement to Mudlet for you, one can be found on the Mudlet forums: https://forums.mudlet.org/viewtopic.php?f=6&t=2853
```
to the description of the video.
